# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('rounds', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='funding date')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.TopList'),
        ),
    ]
