# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplist',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
