# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_toplist_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='toplist',
        ),
    ]
