# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_brief', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_project', models.CharField(max_length=200)),
            ],
        ),
    ]
